### PR TITLE
fix: introduce interfaces to allow mocking in tests

### LINKED ISSUE #134: Expose interfaces when possible
When using this library it's hard to write mocks.
This is due to the fact that some methods expose structs.
```
func (q *Queue) Consumer() *taskq.Consumer {
	if q.consumer == nil {
		q.consumer = taskq.NewConsumer(q)
	}
	return q.consumer
}
```
[see here](https://github.com/vmihailenco/taskq/blob/17eecbcdc4ba18f5c530348f1158aaeae1cda183/azsqs/queue.go#L115)

So I would propose to write interfaces whenever you have objects that provide interactions to allow writing mocks for the API without the need for doing something like described [here](https://travix.io/encapsulating-dependencies-in-go-b0fd74021f5a).

I will prepare a PR containing the changes.

### PR DESCRIPTION
**Pull request by sruehl**
fixes #134

### CODE REVIEW

**Comment by vmihailenco** [comment]
Hi,

Thanks for the PR. It makes sense to use interfaces to accept values as func args, but it does not make sense to return interfaces. See https://bryanftan.medium.com/accept-interfaces-return-structs-in-go-d4cab29a301b

Could you update the PR to follow that principle?

**Comment by sruehl** [comment]
updated following that principle

File: azsqs/queue.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func (q *Queue) Options() *taskq.QueueOptions {
 	return q.opt
 }
 
-func (q *Queue) Consumer() *taskq.Consumer {
+func (q *Queue) Consumer() taskq.QueueConsumer {
```
Comment (vmihailenco) [inline azsqs/queue.go:115]: This looks unneeded, right?

Comment (sruehl) [reply azsqs/queue.go:115]: sadly it is needed as then the azsqs queue won't be accepted anymore as implementation of the Queue interface:
QUEUE_NOT_IMLPEMENTED
`*taskq.Consumer` implements `taskq.QueueConsumer` but Golang doesn't care and only seems to match method signatures.

Comment (vmihailenco) [reply azsqs/queue.go:115]: True, but `Consumer` signature was changed in this PR

```diff
-	Consumer() *Consumer
+	Consumer() QueueConsumer
```

So it should work if we revert that change too. The question is do you need that change for mocking?

Comment (sruehl) [reply azsqs/queue.go:115]: Yes otherwise it's not possible to mock. For example when your code relies on the `Queue` interface you can replace it with a mock, but as soon your code is using `queue.Consumer()` you get in trouble as you can't return a mock here anymore.

Comment (vmihailenco) [reply azsqs/queue.go:115]: Makes sense - thank you.
