### PR TITLE
Prevent taskq cash due to msg.Ctx nil and ack message before delete it

### LINKED ISSUE #150: Encountering  Crash when upgrade to v.3.2.7
```
	
2021/11/09 04:03:04 exit status 2
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:100 +0x309
created by github.com/vmihailenco/taskq/v3/redisq.NewQueue
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:102 +0x90
github.com/vmihailenco/taskq/v3/redisq.NewQueue.func2(0xc00020f290)
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:294 +0x111
github.com/vmihailenco/taskq/v3/redisq.(*Queue).scheduler(0xc00020f290, 0x108c8e0, 0x7, 0xc00182ffa8)
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:437 +0x15a
github.com/vmihailenco/taskq/v3/redisq.(*Queue).withRedisLock(0xc00020f290, 0x11d7130, 0xc000126008, 0xc00003d650, 0x21, 0xc000e9ff38, 0x0, 0x0)
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:296 +0x42
github.com/vmihailenco/taskq/v3/redisq.(*Queue).scheduler.func1(0x11d7130, 0xc000126008, 0x7f66551c35c0, 0xc00159d280)
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:406 +0x318
github.com/vmihailenco/taskq/v3/redisq.(*Queue).schedulePending(0xc00020f290, 0x11d7130, 0xc000126008, 0x84f5e5, 0xc001040b40, 0x11d7130)
/tmp/cache/go-path/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.7/redisq/queue.go:240 +0x1ae
github.com/vmihailenco/taskq/v3/redisq.(*Queue).Release(0xc00020f290, 0xc000dfe5b0, 0x0, 0x0)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/pipeline.go:115 +0x102
github.com/go-redis/redis/v8.(*Pipeline).Exec(0xc000419310, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:604
github.com/go-redis/redis/v8.(*Client).processTxPipeline(...)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:120 +0x2b7
github.com/go-redis/redis/v8.hooks.processTxPipeline(0xc000c00f10, 0x1, 0x1, 0x0, 0x0, 0xc000f3e820, 0x2, 0x2, 0xc00182fbd0, 0xe3214e, ...) 
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:103 +0x32a
github.com/go-redis/redis/v8.hooks.processPipeline(0xc000c00f10, 0x1, 0x1, 0x0, 0x0, 0xc000679040, 0x4, 0x4, 0xc00182fbd0, 0x70, ...)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:396
github.com/go-redis/redis/v8.(*baseClient).processTxPipeline(...)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:404 +0x77
github.com/go-redis/redis/v8.(*baseClient).generalProcessPipeline(0xc000272a60, 0x0, 0x0, 0xc000679040, 0x4, 0x4, 0xc000f22d50, 0x0, 0x0)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:424 +0x113
github.com/go-redis/redis/v8.(*baseClient)._generalProcessPipeline(0xc000272a60, 0x0, 0x0, 0xc000679040, 0x4, 0x4, 0xc000f22d50, 0x10, 0xf5a220)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:274 +0x8a
github.com/go-redis/redis/v8.(*baseClient).withConn(0xc000272a60, 0x0, 0x0, 0xc001040f90, 0x0, 0x0)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:182 +0x66
github.com/go-redis/redis/v8.(*baseClient).getConn(0xc000272a60, 0x0, 0x0, 0x862aa5, 0xc00182f8c8, 0x40f87b)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:194 +0x4c
github.com/go-redis/redis/v8.(*baseClient)._getConn(0xc000272a60, 0x0, 0x0, 0x203000, 0x15, 0x15)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/internal/pool/pool.go:249 +0x58
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).Get(0xc0003d3c20, 0x0, 0x0, 0x0, 0xc00182f7d8, 0x51c116)
/tmp/cache/go-path/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/internal/pool/pool.go:292 +0x37
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).waitTurn(0xc0003d3c20, 0x0, 0x0, 0xc00182f9d0, 0xdef904)
goroutine 254 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7637f7]
```

### PR DESCRIPTION
**Pull request by lilien1010**
close https://github.com/vmihailenco/taskq/issues/150

### CODE REVIEW

File: redisq/queue.go [hunk 1]
```diff
@@ -90,21 +91,31 @@ func NewQueue(opt *taskq.QueueOptions) *Queue {
...
 
+	schedulerDeferFunc := func(name string, wg *sync.WaitGroup) {
+		wg.Done()
+		// Recover from panic. but the panic goroutine is not working anymore
+		// TODO create an extra scheduler once panic happend
+		if err := recover(); err != nil {
+			stack := string(debug.Stack())
+			internal.Logger.Printf("%v,panic recovered: %v,stack=%s", name, err, stack)
+		}
+	}
```
Comment (vmihailenco) [inline redisq/queue.go]: Let's not do this. It hides the problem, not fixes it.

>>Panics are exceptional situations that can leave you app in a broken state. It may be better to let the app crash and restart it then to recover.

File: redisq/queue.go [hunk 2]
```diff
@@ -226,6 +237,11 @@ func (q *Queue) Release(msg *taskq.Message) error {
 	// Make the delete and re-queue operation atomic in case we crash midway
 	// and lose a message.
 	pipe := q.redis.TxPipeline()
+	// When Release a msg, ack it before we delete msg.
+	if err := pipe.XAck(msg.Ctx, q.stream, q.streamGroup, msg.ID).Err(); err != nil {
+		return err
+	}
```
Comment (vmihailenco) [inline redisq/queue.go:232]: :+1:

**Comment by vmihailenco** [comment]
Thanks
